apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-core-baseline-backend-deployment
  namespace: asp-core-baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asp-core-baseline-backend-deployment
  template:
    metadata:
      namespace: asp-core-baseline
      labels:
        app: asp-core-baseline-backend-deployment
    spec:
      containers:
        - name: asp-core-baseline-backend-deployment
          image: localhost:5000/backend:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 80
            protocol: TCP