apiVersion: v1
kind: Service
metadata:
  name: asp-core-baseline-backend-service 
  namespace: asp-core-baseline
spec:
  type: NodePort
  selector: 
    app: asp-core-baseline-backend-deployment
  ports: 
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP